#url:"https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/443711/List_of_Posts_From_May_2015.csv"

#data was downloaded from "https://www.gov.uk/government/publications/list-of-foreign-office-posts"
#was then converted from csv to tsv